---
- name: DYNAMIC REPORTING PART
  hosts: cisco
  gather_facts: no
  connection: network_cli

  roles:
    - ansible-network.network-engine

  tasks:
  - name: CAPTURE SHOW IP INTERFACE
    ios_command:
      commands:
        - show ip interface brief
    register: output

  - name: DISPLAY THE OUTPUT
    debug: var=output.stdout

  - name: PARSE THE RAW OUTPUT
    command_parser:
      file: "./parsers/ios/show_ip_interface_brief.yml"
      content: "{{ output.stdout[0] }}"
  - name: print out data
    debug:
      var: ansible_facts.ip_interface_facts[0].GigabitEthernet1.data.admin_state
