---
- name: GENERATE INTERFACE REPORT
  hosts: rojaslab_routers
  gather_facts: no
  connection: network_cli

  vars:
    destination_ip: 192.168.128.107
    num_pings: 20

  tasks:
    - name: Ping Critial Path
      ios_ping:
        dest: "{{ destination_ip }}"
        count: "{{ num_pings }}"
      register: critical_path

    - name: Display Critical Path Info - packets tx
      debug: 
        var: critical_path.packets_tx

    - name: Display Critical Path Info - packets rx
      debug: 
        var: critical_path.packets_rx

    - name: Display Critical Path Info - packet loss
      debug: 
        var: critical_path.packet_loss
