---
- name: GENERATE INTERFACE REPORT
  hosts: rojaslab_network
  gather_facts: no
  connection: network_cli

  vars:
    output: 

  roles:
    - ansible-network.network-engine

  tasks:
    - name: CAPTURE SHOW HSRP
      ios_command:
        commands:
          - show hsrp
      register: output

    - name: PARSE THE RAW OUTPUT
      command_parser:
        file: "roles/ansible-network.network-engine/parser_templates/ios/testparser_show_hsrp.yml"
        content: "{{ output.stdout[0] }}"

    - name: DISPLAY THE PARSED DATA
      debug:
        var: hsrp_facts