---
- name: GENERATE INTERFACE REPORT
  hosts: rojaslab_routers
  gather_facts: no
  connection: network_cli

  roles:
    - ansible-network.network-engine

  tasks:
    - name: CAPTURE SHOW VERSION
      ios_command:
        commands:
          - show process cpu sorted
      register: output

    - name: PARSE THE RAW OUTPUT
      command_parser:
        file: "roles/ansible-network.network-engine/parser_templates/ios/show_process_cpu.yml"
        content: "{{ output.stdout[0] }}"

    - name: DISPLAY THE PARSED DATA
      debug:
        var: cpu_facts[1] # figure out how to display only 10 or 20 items
